name: CD

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+']
  workflow_dispatch:
    inputs:
      distribution_tag:
        description: 'Distribution tag for npm publish'
        required: true
        default: 'latest'
        type: choice
        options:
          - latest
          - beta
          - alpha

permissions:
  actions: write # Necessary to cancel workflow executions
  checks: write # Necessary to write reports
  contents: read
  id-token: write

jobs:
  publish-npm:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@v5.0.0
        with:
          version: 9
      - name: Setup node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Publish to npm
        run: pnpm publish --provenance --no-git-checks --access public --tag ${{ github.event.inputs.distribution_tag || 'latest' }}
