name: CI

on:
  push:
    branches:
      - main
    paths:
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.css"
  pull_request:
    branches:
      - main
    paths:
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.css"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Setup node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run unit tests
        run: pnpm test
      - name: Run E2E tests
        run: pnpm e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
