name: Tests

on:
	push:
	pull_request:

jobs:
	build:
		runs-on: ubuntu-latest

		strategy:
			matrix:
				node-version: [21.x]

		steps:
		- uses: actions/checkout@v4
		- name: Run tests on Node.js $
			uses: actions/setup-node@v4
			with:
				node-version: $
				cache: 'pnpm'
		- run: pnpm install
		- run: pnpm test